export const VISUAL_FRAMES = [
  { name: "sign-in-desktop", path: "/sign-in", viewport: { width: 1440, height: 1024 }, fixture: "signed-out" },
  { name: "onboarding-connect-mobile", path: "/onboarding/connect", viewport: { width: 390, height: 844 }, fixture: "new-user" },
  { name: "onboarding-goal-mobile", path: "/onboarding/sleep-goal", viewport: { width: 390, height: 844 }, fixture: "onboarding-connect" },
  { name: "onboarding-habits-mobile", path: "/onboarding/habits", viewport: { width: 390, height: 844 }, fixture: "onboarding-goal" },
  { name: "onboarding-profile-mobile", path: "/onboarding/profile", viewport: { width: 390, height: 844 }, fixture: "onboarding-habits" },
  { name: "today-desktop", path: "/today", viewport: { width: 1440, height: 1024 }, fixture: "complete-user" },
  { name: "today-mobile", path: "/today", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "record-desktop", path: "/record", viewport: { width: 1440, height: 1024 }, fixture: "complete-user" },
  { name: "record-mobile", path: "/record", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "caffeine-brand-mobile", path: "/record/caffeine?step=brand", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "caffeine-menu-amount-mobile", path: "/record/caffeine?step=menu-and-amount", viewport: { width: 390, height: 844 }, fixture: "caffeine-brand" },
  { name: "caffeine-confirm-mobile", path: "/record/caffeine?step=confirm", viewport: { width: 390, height: 844 }, fixture: "caffeine-draft" },
  { name: "alcohol-type-mobile", path: "/record/alcohol?step=type", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "alcohol-amount-mobile", path: "/record/alcohol?step=amount", viewport: { width: 390, height: 844 }, fixture: "alcohol-type" },
  { name: "alcohol-confirm-mobile", path: "/record/alcohol?step=confirm", viewport: { width: 390, height: 844 }, fixture: "alcohol-draft" },
  { name: "meal-health-meal-mobile", path: "/record/meal-health?step=meal", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "meal-health-wellness-mobile", path: "/record/meal-health?step=exercise-and-wellness", viewport: { width: 390, height: 844 }, fixture: "meal-health-meal" },
  { name: "meal-health-confirm-mobile", path: "/record/meal-health?step=confirm", viewport: { width: 390, height: 844 }, fixture: "meal-health-draft" },
  { name: "sleep-phone-sleep-mobile", path: "/record/sleep-phone?step=sleep", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "sleep-phone-phone-mobile", path: "/record/sleep-phone?step=phone", viewport: { width: 390, height: 844 }, fixture: "sleep-phone-sleep" },
  { name: "sleep-phone-confirm-mobile", path: "/record/sleep-phone?step=confirm", viewport: { width: 390, height: 844 }, fixture: "sleep-phone-draft" },
  { name: "plan-desktop", path: "/plan", viewport: { width: 1440, height: 1024 }, fixture: "planned-user" },
  { name: "plan-mobile", path: "/plan", viewport: { width: 390, height: 844 }, fixture: "planned-user" },
  { name: "analyze-desktop", path: "/analyze", viewport: { width: 1440, height: 1024 }, fixture: "complete-user" },
  { name: "analyze-mobile", path: "/analyze", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
  { name: "care-desktop", path: "/care", viewport: { width: 1440, height: 1024 }, fixture: "planned-user" },
  { name: "care-mobile", path: "/care", viewport: { width: 390, height: 844 }, fixture: "planned-user" },
  { name: "account-desktop", path: "/account", viewport: { width: 1440, height: 1024 }, fixture: "complete-user" },
  { name: "account-mobile", path: "/account", viewport: { width: 390, height: 844 }, fixture: "complete-user" },
] as const;

export type VisualFrame = (typeof VISUAL_FRAMES)[number];
export type VisualFixture = VisualFrame["fixture"];
