import type { AccountViewModel } from "../application/ports";
import { BottomSheet } from "@/shared/ui/bottom-sheet";
import { ConnectionList } from "./connection-list";
import { DataManagementEntry } from "./data-management-entry";
import { ManualInputRules } from "./manual-input-rules";
import { ProfileForm } from "./profile-form";
import { SleepGoalCard } from "./sleep-goal-card";
import styles from "./account.module.css";

export const AccountScreen = ({ viewModel }: Readonly<{ viewModel: AccountViewModel }>) => <main className={styles.accountLayout}><header className={styles.header}><p className={styles.eyebrow}>ACCOUNT</p><h1>계정 설정</h1><p>내 정보와 수면 목표, 기록 방식의 상태를 확인하세요.</p></header><nav aria-label="계정 설정" className={styles.desktopTabs}><a href="#profile">개인 정보</a><a href="#goal">수면 목표</a><a href="#connections">연결 관리</a><a href="#data">데이터 관리</a></nav><div className={styles.desktopDetails}><section id="profile" className={styles.card}><h2>개인 정보</h2><ProfileForm identity={viewModel.identity} profile={viewModel.profile} /></section><section id="goal" className={styles.card}><h2>수면 목표</h2><SleepGoalCard goal={viewModel.sleepGoal} /></section><section id="connections" className={styles.card}><h2>연결 관리</h2><ConnectionList connections={viewModel.connections} /><ManualInputRules categories={viewModel.manualInputCategories} /></section></div><div className={styles.mobileDetails}><section className={styles.summaryCard}><h2>개인 정보</h2><p>{viewModel.profile.nickname} · {viewModel.profile.timezone}</p><BottomSheet triggerLabel="개인 정보 수정"><ProfileForm identity={viewModel.identity} profile={viewModel.profile} /></BottomSheet></section><section className={styles.summaryCard}><h2>수면 목표</h2><p>{viewModel.sleepGoal.targetBedTime} 취침 · {viewModel.sleepGoal.targetWakeTime} 기상</p><BottomSheet triggerLabel="수면 목표 수정"><SleepGoalCard goal={viewModel.sleepGoal} /></BottomSheet></section><section className={styles.summaryCard}><h2>연결 관리</h2><p>직접 입력만 사용 중입니다.</p><BottomSheet triggerLabel="연결·직접 입력 보기"><ConnectionList connections={viewModel.connections} /><ManualInputRules categories={viewModel.manualInputCategories} /></BottomSheet></section></div><div id="data"><DataManagementEntry reauth={viewModel.dataManagement} /></div></main>;
